### ISSUE TITLE
When logging in.

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#15]
i created some Testtickets..
normaly i should get informed on Login..but

instead of this i get an empty line

![image](https://user-images.githubusercontent.com/12080017/46534841-d5651580-c8a9-11e8-9ab0-62d8a176af32.png)

This is only the inform measge.

if a ticket is flagged then i get the meassge that an ticket is flags on login

**Comment by SuperRonanCraft** [comment]
How many tickets are open/flagged when this so called blank message popped up upon login?
Cause i've never seen this before

**Comment by CloudeLecaw** [comment]
just one opened... unflags and this pops up to me :(

**Comment by CloudeLecaw** [comment]
Edit:
The error still exists in 2.6.2

**Comment by CloudeLecaw** [comment]
Wait…
the Problem is not that there is an empty line…
...
The Problem is that instead of this emptry line on Login i should see a text like "There is currently one open ticket"


This was working in Version 5.5.x

**Comment by SuperRonanCraft** [comment]
Can you get me a copy of ur lang file? Preferable in yaml format or in a Hastebin

**Comment by CloudeLecaw** [comment]
well of curse i can :) i will send it to you when i am home :)

What i tested allready - it happens also when i use /modreq language en to use the english langfile.
I will take a look when i am home aggain if there are differences between my de file and a Fresh generated english one.

**Comment by CloudeLecaw** [comment]
im running a  1.13.1 Spigot Testserver on a Windows 10 x64 Machine.

**Comment by SuperRonanCraft** [comment]
Alright, are you running it on a MySQL database?

**Comment by CloudeLecaw** [comment]
no. im using the flat files

**Comment by SuperRonanCraft** [comment]
Alright, I've been testing it on MySQL cause it's the most buggy ATM, let me see if I can find the issue

**Comment by CloudeLecaw** [comment]
Well today i also got an error on login, may it helps 🥉 
```
[20:32:41] [User Authenticator #11/INFO]: UUID of player Cloude_Lecaw is f24df990-9c6b-4f32-938a-4c91a26d31f4
[20:32:43] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to AdvancedModreq v5.6.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:344) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
	at me.superronancraft.advancedmodreq.references.information.Broadcast.joinPlayer(Broadcast.java:291) ~[?:?]
	at me.superronancraft.advancedmodreq.events.player.Join.join(Join.java:42) ~[?:?]
	at me.superronancraft.advancedmodreq.events.player.Listen.join(Listen.java:32) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-02518f9]
	... 14 more
```

**Comment by SuperRonanCraft** [comment]
Very weird u got that Mojang authentication error, that now just means I need to check for potential errors on the login event

**Comment by CloudeLecaw** [comment]
Well today my owner setuped up for us a Testserver. may the error with the empty line is not there.
We will see, i will report you :§
