### ISSUE TITLE
Problem with opening second page on gui

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SuperRonanCraft/AdvancedModreq#17]
As the title says, its not working:

```11.10 17:18:13 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedModreq v5.6.2
11.10 17:18:13 [Server] INFO org.bukkit.event.EventException: null
11.10 17:18:13 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2257) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
11.10 17:18:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
11.10 17:18:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
11.10 17:18:13 [Server] INFO Caused by: java.lang.IllegalArgumentException: Illegal group reference
11.10 17:18:13 [Server] INFO at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_181]
11.10 17:18:13 [Server] INFO at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_181]
11.10 17:18:13 [Server] INFO at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_181]
11.10 17:18:13 [Server] INFO at me.superronancraft.advancedmodreq.references.items.Placeholders.checkPH(Placeholders.java:259) ~[?:?]
11.10 17:18:13 [Server] INFO at me.superronancraft.advancedmodreq.references.items.Placeholders.lambda$checkItemPH$0(Placeholders.java:193) ~[?:?]
11.10 17:18:13 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
11.10 17:18:13 [Server] INFO at me.superronancraft.advancedmodreq.references.items.Placeholders.checkItemPH(Placeholders.java:192) ~[?:?]
11.10 17:18:13 [Server] INFO at me.superronancraft.advancedmodreq.inventories.global.ListInv.createMenu(ListInv.java:109) ~[?:?]
11.10 17:18:13 [Server] INFO at me.superronancraft.advancedmodreq.events.player.Click.list(Click.java:187) ~[?:?]
```

**Comment by SuperRonanCraft** [comment]
I can't quite tell you the reason for this error besides just having an invalid ticket message, if this error continues try to give me a visual in-game error :)
