### ISSUE TITLE
inventorycloseevent

### ISSUE THREAD

**Issue by untuned** [SuperRonanCraft/AdvancedModreq#32]
**Plugin Version**:

5.12.1

**Describe The Bug**:

just an error in console when closing the inventory

**How To Reproduce**:

1. `/modreq manage` (empty)
2. press escape

**Expected Behavior**:

no error

**Screenshots/Error Log**:

```
[21:04:54] [Server thread/INFO]: untuned issued server command: /modreq list
[21:04:56] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to AdvancedModreq v5.12.1
java.lang.NullPointerException: null
	at me.superronancraft.advancedmodreq.events.player.Exit.exit(Exit.java:16) ~[?:?]
	at me.superronancraft.advancedmodreq.events.player.Listen.exit(Listen.java:49) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-87]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:561) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1370) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2107) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-87]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```
**Additional Context**:

why is `/modreq manage` empty?

**Comment by SuperRonanCraft** [comment]
This feature is in high developement, it got leaked out by mistake. This command will be disabled on the next patch until I'm able to continue developing this command feature :)
