### ISSUE TITLE
issue with the converter

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#37]
```
[11:27:00 ERROR]: Error occurred while enabling AdvancedModreqSqliteConverter v1.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketManager.saveTicket(me.superronancraft.advancedmodreq.references.systems.internal.tickets.Ticket)'
	at me.superronancraft.advancedmodreq_sqliteconverter.Main.convert(Main.java:57) ~[?:?]
	at me.superronancraft.advancedmodreq_sqliteconverter.Main.onEnable(Main.java:23) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-331]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-331]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-331]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-331]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-331]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-331]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[11:27:00 INFO]: Disabling AdvancedModreqSqliteConverter v1.0
```

**Comment by SuperRonanCraft** [comment]
Hey @CloudeLecaw I do believe this version of the converter was updated to 6.0.1 without warning, just make sure you have the latest version of AdvancedModreq installed

**Comment by CloudeLecaw** [comment]
worked fine <3
