### ISSUE TITLE
issue from updateing from 6.0.2 to 6.10

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#39]
After upgrading from 6.0.2 to 6.1.0 we get this error on ticket creation
(only downgrding to 6.0.2 solves it)

```
[21:38:51] [Server thread/INFO]: Kathriniiiii issued server command: /ticket Hallo klappt es jetzt mit dem Ticket?
[21:38:51] [Server thread/ERROR]: [AdvancedModreq] Couldn't execute MySQL statement: 
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (19 values for 20 columns)
	at org.sqlite.core.DB.newSQLException(DB.java:1012) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.core.DB.throwex(DB.java:989) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.core.DB.prepare(DB.java:257) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[patched_1.16.5.jar:git-Paper-468]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[patched_1.16.5.jar:git-Paper-468]
	at me.superronancraft.advancedmodreq.references.systems.database.Database.sqlUpdate(Database.java:327) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.database.Database.createTicket(Database.java:210) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketCore.saveTicket(TicketCore.java:134) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketCreator.confirmCreate(TicketCreator.java:89) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketCreator.create(TicketCreator.java:54) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.commands.CmdCreate.chatEvent(CmdCreate.java:45) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.commands.CmdCreate.execute(CmdCreate.java:26) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.commands.ModreqCommands.execute(ModreqCommands.java:53) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.Commands.onCommand(Commands.java:24) ~[?:?]
	at me.superronancraft.advancedmodreq.AdvancedModreq.onCommand(AdvancedModreq.java:76) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by SuperRonanCraft** [comment]
Oh whoops, I will get a patch out later today fixing this

**Comment by SuperRonanCraft** [comment]
Fixed :) https://www.spigotmc.org/resources/advanced-mod-request.40528/update?update=387737
