### ISSUE TITLE
[BUG] Critical bug in the REPLY system

### ISSUE THREAD

**Issue by Fargus5** [SuperRonanCraft/AdvancedModreq#40]
**Plugin Version**:

latest

**Describe The Bug**:

when you click on buttons in the reply GUI, nothing happen.

**How To Reproduce**:

Open a ticket, go to the reply section... only the "add' button works.
the back button is broken and also the "read full message" doesn't work

**Expected Behavior**:

**Screenshots/Error Log**:

```

[20:05:44] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedModreq v6.1.1
--
15867 | java.lang.NullPointerException: null
15868 | at me.superronancraft.advancedmodreq.menus.inventories.InvReplies.clickEvent(InvReplies.java:128) ~[?:?]
15869 | at me.superronancraft.advancedmodreq.menus.enums.ModreqInv.clickEvent(ModreqInv.java:108) ~[?:?]
15870 | at me.superronancraft.advancedmodreq.events.player.Click.click(Click.java:17) ~[?:?]
15871 | at me.superronancraft.advancedmodreq.events.player.Listen.click(Listen.java:39) ~[?:?]
15872 | at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.3.jar:git-Paper-253]
15873 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
15874 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
15875 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
15876 | at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2437) ~[patched_1.16.3.jar:git-Paper-253]
15877 | at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-253]
15878 | at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-253]
15879 | at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-253]
15880 | at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-253]
15881 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-253]
15882 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-253]
15883 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-253]
15884 | at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-253]
15885 | at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-253]
15886 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-253]
15887 | at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-253]
15888 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-253]
15889 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
15890 | at java.lang.Thread.run(Thread.java:834) [?:?]


```

**Additional Context**:

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
After some test, I noticed that the problem is when you open a ticket like this:

/report view 11

in this area the reply section doesn't work.

Instead if you do: /report list... or /report status... in this area it works.

**Comment by Fargus5** [comment]
I noticed that there is no way to RESOLVE  a ticket...

I tried everything but I didn't understand how to resolve the ticket.

I can reply, close, but how to resolve?

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I noticed that the resolve function doesn't work...
I tried to follow the step suggested here - Resolve: A resolved ticket allows players to rate their experience, but only if the ticket was closed and an admin left a reply on the ticket.

But it doesn't resolve the ticket...

**Comment by SuperRonanCraft** [comment]
Woah, very sorry for the very long delay, I have been in a development hiatus. I will be getting back into the rhythm of things and hopefully get this patched out very soon!

**Comment by SuperRonanCraft** [comment]
fixed the multiple bugs you mentioned above ;)
