### ISSUE TITLE
Missing the authors name

### ISSUE THREAD

**Issue by mare-on** [SuperRonanCraft/AdvancedModreq#41]
**Plugin Version**: 6.1.1

**Describe The Bug**: MySQL issue while inserting new ticket.

**How To Reproduce**: Send new ticket.

**Expected Behavior**: Log new ticket into MySQL database.

**Screenshots/Error Log**:
```
[02:25:44] [Server thread/ERROR]: [AdvancedModreq] Couldn't execute MySQL statement: 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'name' in 'field list'
	at sun.reflect.GeneratedConstructorAccessor108.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055) ~[patched_1.16.5.jar:git-Paper-469]
	at me.superronancraft.advancedmodreq.references.systems.database.Database.sqlUpdate(Database.java:339) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.database.Database.createTicket(Database.java:213) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketCore.saveTicket(TicketCore.java:134) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketCreator.confirmCreate(TicketCreator.java:89) ~[?:?]
	at me.superronancraft.advancedmodreq.references.systems.internal.tickets.TicketCreator.create(TicketCreator.java:54) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.commands.CmdCreate.chatEvent(CmdCreate.java:45) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.commands.CmdCreate.execute(CmdCreate.java:26) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.commands.ModreqCommands.execute(ModreqCommands.java:53) ~[?:?]
	at me.superronancraft.advancedmodreq.events.cmd.Commands.onCommand(Commands.java:24) ~[?:?]
	at me.superronancraft.advancedmodreq.AdvancedModreq.onCommand(AdvancedModreq.java:76) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:758) ~[patched_1.16.5.jar:git-Paper-469]
	at com.mtihc.minecraft.treasurechest.v8.rewardfactory.rewards.CommandReward.give(CommandReward.java:116) ~[?:?]
	at com.mtihc.minecraft.treasurechest.v8.core.TreasureManager.giveRewards(TreasureManager.java:736) ~[?:?]
	at com.mtihc.minecraft.treasurechest.v8.core.TreasureManager.openTreasureInventory(TreasureManager.java:342) ~[?:?]
	at com.mtihc.minecraft.treasurechest.v8.core.TreasureManager.onPlayerInteract(TreasureManager.java:250) ~[?:?]
	at com.mtihc.minecraft.treasurechest.v8.core.TreasureChestListener.onPlayerInteract(TreasureChestListener.java:66) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-469]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:528) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-469]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Additional Context**: Downgrade to version 6.0.2 works well.

**Comment by SuperRonanCraft** [comment]
New columns are generated on plugin boot up. So this might be a mysql permission issue, try allowing the mysql user to add columns and alter the table so it can add the missing column

**Comment by mare-on** [comment]
I have huge relational database and I never had any permissions issues with other plugins. My user has permissions to modify every table so I don't think that there is any problem. I can try to add new column "name" manually into "report_data" but I need to know if there are defined any rules in Java code about... position of the column and data type.

**Comment by SuperRonanCraft** [comment]
I've checked numerous times and the java code creates the column automatically, I would remove the column manually and restart the server and check the mysql database as see if the column is created. I've checked multiple times and the "name" column is being generated on both online mysql and offline sqlite databases. Give it another shot, if it doesnt work, the best thing would be is to start from scratch with another table and see if all the columns are generated

**Comment by SuperRonanCraft** [comment]
Okay, I was able to find the issue, if the database was not created recently in 6.1.0, it would alter the table "AMR_Data" instead of a custom table given under the mysql.yml file.
I just uploaded a patch fixing this up ;)
https://www.spigotmc.org/resources/advanced-mod-request.40528/update?update=388080
